### ISSUE TITLE
Is JustEnoughCalculation-1.7.10-3.8.3 compatible with NotEnoughItems-1.7.10-2.1.18-GTNH?

### ISSUE THREAD

**Issue by hoshinokiseki** [Towdium/JustEnoughCalculation#105]
I'm using Just enough calculation as [[Tutorial] General Usage](https://github.com/Towdium/JustEnoughCalculation/issues/85). But game crash and here is part of crash log.

    java.lang.NoSuchMethodError: java.lang.Math.multiplyExact(JI)J
    at me.towdium.jecalculation.data.label.ILabel$Impl.lambda$form$0(ILabel.java:489)
	at me.towdium.jecalculation.data.label.ILabel$Merger.merge(ILabel.java:149)
	at me.towdium.jecalculation.data.structure.Recipe.lambda$matches$10(Recipe.java:135)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findAny(Unknown Source)
	at me.towdium.jecalculation.data.structure.Recipe.matches(Recipe.java:135)
	at me.towdium.jecalculation.data.structure.CostList$Calculator.find(CostList.java:171)
	at me.towdium.jecalculation.data.structure.CostList$Calculator.<init>(CostList.java:124)
	at me.towdium.jecalculation.data.structure.CostList.calculate(CostList.java:102)
	at me.towdium.jecalculation.gui.guis.GuiCraft.refreshCalculator(GuiCraft.java:142)
	at me.towdium.jecalculation.gui.guis.GuiCraft.refreshLabel(GuiCraft.java:187)
	at me.towdium.jecalculation.gui.guis.GuiCraft.lambda$new$0(GuiCraft.java:39)
	at me.towdium.jecalculation.gui.widgets.WLabel.notifyUpdate(WLabel.java:177)
	at me.towdium.jecalculation.gui.widgets.WLabel.onMouseClicked(WLabel.java:111)
	at me.towdium.jecalculation.gui.widgets.WContainer.lambda$onMouseClicked$1(WContainer.java:57)
	at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.anyMatch(Unknown Source)
	at me.towdium.jecalculation.gui.widgets.WContainer.onMouseClicked(WContainer.java:57)
	at me.towdium.jecalculation.gui.widgets.WContainer.lambda$onMouseClicked$1(WContainer.java:57)
	at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.anyMatch(Unknown Source)
	at me.towdium.jecalculation.gui.widgets.WContainer.onMouseClicked(WContainer.java:57)
	at me.towdium.jecalculation.gui.JecaGui.onMouse(JecaGui.java:110)
	at me.towdium.jecalculation.event.handlers.NEIEventHandler.mouseClicked(NEIEventHandler.java:47)
	at codechicken.nei.guihook.GuiContainerManager.mouseClicked(GuiContainerManager.java:333)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by Discreater** [comment]
Sorry, I made the mistake of building this version using java11. I will upload corrrect build version later (1.7.10-3.8.4). And the version 1.7.10-3.8.3 has been archived.
