### ISSUE TITLE
GTNH 2.6.1 "recipe cannot be transferred to the calculator"

### ISSUE THREAD

**Issue by SkilledAlpaca** [Towdium/JustEnoughCalculation#162]
Mod Version: 3.8.5
GTNH Version: 2.6.1

This is a two part issue. 

The Import recipe button is missing on machine based recipes. 
![image](https://github.com/Towdium/JustEnoughCalculation/assets/26860324/098cee9e-319d-4f6a-9f74-945ed5873bb0)

Attempting to add the Basic Forge Hammer, it still adds the recipe but thought I would report this in case it's elsewhere or doesn't work. 
```java
[16:46:07] [Client thread/INFO]: [CHAT] Calculator: Sorry, the recipe cannot be transferred to the calculator. It would be great if you could provide log files to help us fix it
[16:46:07] [Client thread/ERROR] [jecalculation]: Exception when handling recipe: codechicken.nei.recipe.ShapedRecipeHandler
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.isInstance(Object)" because "me.towdium.jecalculation.nei.adapter.GregTech.gtAssLine" is null
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//me.towdium.jecalculation.nei.adapter.GregTech.handleRecipe(GregTech.java:65)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//me.towdium.jecalculation.nei.Adapter.handleRecipe(Adapter.java:85)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//me.towdium.jecalculation.nei.JecaOverlayHandler.convertRecipe(JecaOverlayHandler.java:47)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//me.towdium.jecalculation.nei.JecaOverlayHandler.overlayRecipe(JecaOverlayHandler.java:34)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//codechicken.nei.recipe.GuiRecipe.overlayRecipe(GuiRecipe.java:852)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//codechicken.nei.recipe.GuiRecipe.func_146284_a(GuiRecipe.java:764)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:326)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//codechicken.nei.recipe.GuiRecipe.func_73864_a(GuiRecipe.java:697)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5110)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.main.Main.main(SourceFile:148)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-System//net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-System//net.minecraft.launchwrapper.Launch.launch(Launch.java:35)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-System//net.minecraft.launchwrapper.Launch.main(Launch.java:60)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:219)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-System//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-System//org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
[16:46:07] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-System//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

Attempting to add the vanilla Anvil recipe. 
```java
[16:51:11] [Client thread/INFO]: [CHAT] Calculator: Sorry, the recipe cannot be transferred to the calculator. It would be great if you could provide log files to help us fix itÂ§7 (2)
[16:51:11] [Client thread/ERROR] [jecalculation]: Exception when handling recipe: codechicken.nei.recipe.ShapedRecipeHandler
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.isInstance(Object)" because "me.towdium.jecalculation.nei.adapter.GregTech.gtAssLine" is null
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//me.towdium.jecalculation.nei.adapter.GregTech.handleRecipe(GregTech.java:65)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//me.towdium.jecalculation.nei.Adapter.handleRecipe(Adapter.java:85)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//me.towdium.jecalculation.nei.JecaOverlayHandler.convertRecipe(JecaOverlayHandler.java:47)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//me.towdium.jecalculation.nei.JecaOverlayHandler.overlayRecipe(JecaOverlayHandler.java:34)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//codechicken.nei.recipe.GuiRecipe.overlayRecipe(GuiRecipe.java:852)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//codechicken.nei.recipe.GuiRecipe.func_146284_a(GuiRecipe.java:764)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:326)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//codechicken.nei.recipe.GuiRecipe.func_73864_a(GuiRecipe.java:697)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5110)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//net.minecraft.client.main.Main.main(SourceFile:148)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-System//net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-System//net.minecraft.launchwrapper.Launch.launch(Launch.java:35)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-System//net.minecraft.launchwrapper.Launch.main(Launch.java:60)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:219)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-System//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-System//org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
[16:51:11] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-System//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by Discreater** [comment]
Have you tried using jeca version 3.8.6? This version might be compatible and solve the problem.

**Comment by SkilledAlpaca** [comment]
3.8.6 appears to be working. No errors thrown and I am able to add machine recipes as well. Thank you!
