### ISSUE TITLE
[1.7.10] NullPointerException when player is dead

### ISSUE THREAD

**Issue by the-vindex** [Towdium/JustEnoughCalculation#47]
Hi,

It's not entirely easily reproducible so I'm not attaching full log (it's Long), but when player is dead, he gets crashed looped from the server until server is restarted.

Exception is plus minus clear, see below.

V.

[00:54:39] [NEI Item Filtering/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.ItemTooltipEvent@15c43a80:
java.lang.NullPointerException
	at pers.towdium.justEnoughCalculation.event.PlayerEventHandler.onTooltip(PlayerEventHandler.java:36) ~[PlayerEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_2096_PlayerEventHandler_onTooltip_ItemTooltipEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:169) [ForgeEventFactory.class:?]
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:626) [add.class:?]
	at codechicken.nei.guihook.GuiContainerManager.itemDisplayNameMultiline(GuiContainerManager.java:119) [GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.concatenatedDisplayName(GuiContainerManager.java:162) [GuiContainerManager.class:?]
	at codechicken.nei.api.ItemInfo.getSearchName(ItemInfo.java:529) [ItemInfo.class:?]
	at codechicken.nei.ItemList$PatternItemFilter.matches(ItemList.java:65) [ItemList$PatternItemFilter.class:?]
	at codechicken.nei.ItemList$AnyMultiItemFilter.matches(ItemList.java:110) [ItemList$AnyMultiItemFilter.class:?]
	at codechicken.nei.ItemList$AllMultiItemFilter.matches(ItemList.java:85) [ItemList$AllMultiItemFilter.class:?]
	at codechicken.nei.ItemList$2.execute(ItemList.java:239) [ItemList$2.class:?]
	at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24) [RestartableTask$1.class:?]

**Comment by Towdium** [comment]
Hmmmm..... I'm really sorry, but it's so long ago, even myself have no idea about the implementations in that version. So I'm afraid it won't get fixed.
