### ISSUE TITLE
Crash due to config/jecalculation directory not existing.

### ISSUE THREAD

**Issue by rallias** [Towdium/JustEnoughCalculation#65]
```
[09Jan2020 22:59:48.915] [Client thread/FATAL] [net.minecraft.client.Minecraft/]: Reported exception thrown!
net.minecraft.crash.ReportedException: Rendering overlay
        at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:548) ~[?:?]
        at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890) ~[?:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) ~[?:?]
        at net.minecraft.client.main.Main.main(SourceFile:155) ~[1.14.4-forge-28.1.113.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242-ea]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242-ea]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242-ea]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242-ea]
        at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.14.4-28.1.113.jar:28.1]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?]
Caused by: com.electronwill.nightconfig.core.io.WritingException: An I/O error occured
        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:222) ~[core-3.6.0.jar:?]
        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.0.jar:?]
        at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.0.jar:?]
        at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.0.jar:?]
        at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:53) ~[?:?]
        at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:99) ~[?:?]
        at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_242-ea]
        at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2064) ~[?:1.8.0_242-ea]
        at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83) ~[?:?]
        at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:152) ~[?:?]
        at net.minecraftforge.fml.client.ClientModLoader.lambda$startModLoading$6(ClientModLoader.java:123) ~[?:?]
        at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?]
        at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:123) ~[?:?]
        at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:105) ~[?:?]
        at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_242-ea]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_242-ea]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_242-ea]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_242-ea]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_242-ea]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_242-ea]
Caused by: java.nio.file.NoSuchFileException: /home/rallias/.minecraft/wondermentamuseful/config/jecalculation/config.toml
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_242-ea]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_242-ea]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_242-ea]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_242-ea]
        at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_242-ea]
        at java.nio.file.Files.createFile(Files.java:632) ~[?:1.8.0_242-ea]
        at net.minecraftforge.fml.config.ConfigFileTypeHandler.setupConfigFile(ConfigFileTypeHandler.java:71) ~[?:?]
        at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$null$0(ConfigFileTypeHandler.java:49) ~[?:?]
        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:215) ~[core-3.6.0.jar:?]
        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.0.jar:?]
        at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.0.jar:?]
        at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.0.jar:?]
        at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:53) ~[?:?]
        at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:99) ~[?:?]
        at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_242-ea]
        at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2064) ~[?:1.8.0_242-ea]
        at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83) ~[?:?]
        at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:152) ~[?:?]
        at net.minecraftforge.fml.client.ClientModLoader.lambda$startModLoading$6(ClientModLoader.java:123) ~[?:?]
        at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?]
        at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:123) ~[?:?]
        at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:105) ~[?:?]
        at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_242-ea]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_242-ea]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_242-ea]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_242-ea]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_242-ea]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_242-ea]
```

Creating config/jecalculation directory allows game to launch fully.

**Comment by Towdium** [comment]
Thanks for report!

I'm not so sure how this exception happens. It might be forge making changes to the config system. I will look into it.

**Comment by Towdium** [comment]
It seems not related to forge. I don't know why I skipped this crash, but it should be fixed now. Let me know if it still crashes.
