### ISSUE TITLE
Possibly world breaking error

### ISSUE THREAD

**Issue by Xireka** [Towdium/JustEnoughCalculation#8]
I tried using your mod and by mistake typed a letter into the black bar in the calculator GUI.

That crashed my game, I reloaded and tried deleting it which again, crashed my game.
Now every time I try to load that world it crashes and doesn't even try loading the world.

Here is the important part of the crash:

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 14.05.16 23:01
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at pers.towdium.justEnoughCalculation.core.ItemRecord.<init>(ItemRecord.java:35)
	at pers.towdium.justEnoughCalculation.core.Calculator.<init>(Calculator.java:22)
	at pers.towdium.justEnoughCalculation.gui.guis.calculator.GuiCalculator.refreshRecipe(GuiCalculator.java:405)
	at pers.towdium.justEnoughCalculation.gui.guis.calculator.GuiCalculator.func_73869_a(GuiCalculator.java:298)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475)
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

So yeah, your mod and the idea behind it is great but right now I'm scared of using it honestly if it's going to break my worlds, maybe I should have typed anything into that bar but even then I'm not sure that it wouldn't crash :/

**Comment by Towdium** [comment]
Thanks for report.
I will definitely look into this issue as soon as possible.
For the time being, just delete the mod, then maybe you can load the world.
Actually, the mod doesn't store any information in the world data except items, so it shouldn't break the world save.

**Comment by Towdium** [comment]
By the way, which version are you using？ 1.7 or 1.8？

**Comment by Xireka** [comment]
My bad, I forgot to mention, I was using the latest version for 1.7.10.

I also noticed a new version just got released 9 minutes ago on curseforge, from the change log I'm taking it's the fix for my crash apparently, you're fast :D. I'll test it quickly and report if it works :)

**Comment by Towdium** [comment]
Actually I think this bug will only cause crash when openning the GUI.
So if your game crashes when entering the world, I have no idea about that.
It is possible that some data of the world is damaged when the game crashes.
So do let me know about the progress.

**Comment by Xireka** [comment]
The crash is fixed but this might sound silly, I don't get the mod to work.

I open the calculator, drag and drop an item into the top left slot. Say I want that 1 time. The calculator adds the item but only shows the completed item inside the bottom space, and only in input.

I tried both with modded as with vanilla items :/

**Comment by Towdium** [comment]
I see, I have been asked similar questions several times.
You need to record some recipes to get started. I know this may be silly, but if you are in a client with tons of mods, every item could have many recipes, then the mod will get confused which recipe to use. You can refer to the video in the publish page or [click here](https://www.youtube.com/watch?v=O-VCGAgBEmI). It will tell you how to input recipes. The video is for 1.8.9 and not recently updated, but the way to use is still very similar.

**Comment by Xireka** [comment]
Oh the video helps thank you.

Sadly when trying to add a recipe I can't press R, nothing happens so I can't transfer the recipe to the calculator :(

I don't know why

**Comment by Towdium** [comment]
Oh! In 1.7 version simply use left click to check the recipe instead "R". 
Not sure why "R" doesn't work in the GUI, but mine is the same.
